title:       "Vivek Raj"
description: "PhD Researcher in Biomedical Engineering | Image Processing & Motion Intent Detection"
url:         "https://vivekrajbme.github.io"
baseurl:     ""       # no leading slash

# -----------------------------------------------------------------------------
# Remote Theme & Plugins
# -----------------------------------------------------------------------------
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# -----------------------------------------------------------------------------
# Markdown & Permalinks
# -----------------------------------------------------------------------------
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
include:
  - _pages
  - _posts
  
---

